# This is a Terragrunt module generated by boilerplate.
terraform {
  source = "git::https://github.com/gruntwork-io/terraform-aws-ecs.git//.//modules/ecs-cluster?ref=v0.38.1"
}

include "root" {
  path = find_in_parent_folders()
}

dependency "vpc" {
  config_path = "../vpc"

  mock_outputs = {
    vpc_id = "fake-vpc-id"
    private_app_subnets = {}
  }
}

inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------

  # Description: The name of the ECS cluster (e.g. ecs-prod). This is used to namespace all the resources created by these templates.
  # Type: string
  cluster_name = "{{ .ClusterName }}"

  # Description: The minimum number of EC2 Instances launchable for this ECS Cluster. Useful for auto-scaling limits.
  # Type: number
  cluster_min_size = 1

  # Description: The maximum number of EC2 Instances that must be running for this ECS Cluster. We recommend making this twice var.cluster_min_size, even if you don't plan on scaling the cluster up and down, as the extra capacity will be used to deploy udpates to the cluster.
  # Type: number
  cluster_max_size = 2

  # Description: The AMI to run on each of the ECS Cluster's EC2 Instances.
  # Type: string
  cluster_instance_ami =  "ami-04ad88191cb68d4fd"

  # Description: The type of EC2 instance to run for each of the ECS Cluster's EC2 Instances (e.g. t2.medium).
  # Type: string
  cluster_instance_type = "t2.medium"

  # Description: The EC2 Keypair name used to SSH into the ECS Cluster's EC2 Instances.
  # Type: string
  cluster_instance_keypair_name = null

  # Description: The ID of the VPC in which the ECS Cluster's EC2 Instances will reside.
  # Type: string
  vpc_id = dependency.vpc.outputs.vpc_id

  # Description: A list of the subnets into which the ECS Cluster's EC2 Instances will be launched. These should usually be all private subnets and include one in each AWS Availability Zone.
  # Type: list
  vpc_subnet_ids = keys(dependency.vpc.outputs.private_app_subnets)


  # --------------------------------------------------------------------------------------------------------------------
  # Optional input variables
  # Uncomment the ones you wish to set
  # --------------------------------------------------------------------------------------------------------------------

  # Description: The size in GB of the root volume for each of the ECS Cluster's EC2 Instances
  # Type: number
  # cluster_instance_root_volume_size = 40

  # Description: The volume type for the root volume for each of the ECS Cluster's EC2 Instances. Can be standard, gp2, or io1
  # Type: string
  # cluster_instance_root_volume_type = "gp2"

  # Description: Set to true to encrypt the root block devices for the ECS cluster's EC2 instances
  # Type: bool
  # cluster_instance_root_volume_encrypted = false

  # Description: Set to true to request spot instances. Set cluster_instance_spot_price variable to set a maximum spot price limit.
  # Type: bool
  # cluster_instance_request_spot_instances = false

  # Description: Value is the maximum bid price for the instance on the EC2 Spot Market.
  # Type: string
  # cluster_instance_spot_price = null

  # Description: Enables/disables detailed CloudWatch monitoring for EC2 instances
  # Type: bool
  # cluster_detailed_monitoring = true

  # Description: Passthrough to aws_launch_template resource.  Associate a public ip address with EC2 instances in cluster
  # Type: bool
  # cluster_instance_associate_public_ip_address = false

  # Description: If true, the launched EC2 instance will be EBS-optimized
  # Type: bool
  # cluster_instance_ebs_optimized = false

  # Description: When set, name the IAM role for the ECS cluster using this variable. When null, the IAM role name will be derived from var.cluster_name.
  # Type: string
  # custom_iam_role_name = null

  # Description: The User Data script to run on each of the ECS Cluster's EC2 Instances on their first boot.
  # Type: string
  # cluster_instance_user_data = null

  # Description: The base64-encoded User Data script to run on the server when it is booting. This can be used to pass binary User Data, such as a gzipped cloud-init script. If you wish to pass in plain text (e.g., typical Bash script) for User Data, use var.cluster_instance_user_data instead.
  # Type: string
  # cluster_instance_user_data_base64 = null

  # Description: The port to use for SSH access.
  # Type: number
  # ssh_port = 22

  # Description: The IP address ranges in CIDR format from which to allow incoming SSH requests to the ECS instances.
  # Type: list
  # allow_ssh_from_cidr_blocks = []

  # Description: The IDs of security groups from which to allow incoming SSH requests to the ECS instances.
  # Type: list
  # allow_ssh_from_security_group_ids = []

  # Description: A list of Security Group IDs of the ALBs which will send traffic to this ECS Cluster.
  # Type: list
  # alb_security_group_ids = []

  # Description: The tenancy of the servers in this cluster. Must be one of: default, dedicated, or host.
  # Type: string
  # tenancy = "default"

  # Description: Set this variable to true to enable the Instance Metadata Service (IMDS) endpoint, which is used to fetch information such as user-data scripts, instance IP address and region, etc. Set this variable to false if you do not want the IMDS endpoint enabled for instances launched into the Auto Scaling Group for the workers.
  # Type: bool
  # enable_imds = true

  # Description: Set this variable to true to enable the use of Instance Metadata Service Version 1 in this module's aws_launch_template. Note that while IMDsv2 is preferred due to its special security hardening, we allow this in order to support the use case of AMIs built outside of these modules that depend on IMDSv1.
  # Type: bool
  # use_imdsv1 = true

  # Description: The desired HTTP PUT response hop limit for instance metadata requests.
  # Type: number
  # http_put_response_hop_limit = null

  # Description: Custom tags to apply to the ECS cluster
  # Type: map
  # custom_tags_ecs_cluster = {}

  # Description: A list of custom tags to apply to the EC2 Instances in this ASG. Each item in this list should be a map with the parameters key, value, and propagate_at_launch.
  # Type: list
  # custom_tags_ec2_instances = []

  # Description: A map of custom tags to apply to the Security Group for this ECS Cluster. The key is the tag name and the value is the tag value.
  # Type: map
  # custom_tags_security_group = {}

  # Description: A list of policies to decide how the instances in the auto scale group should be terminated. The allowed values are OldestInstance, NewestInstance, OldestLaunchConfiguration, ClosestToNextInstanceHour, OldestLaunchTemplate, AllocationStrategy, Default. If you specify more than one policy, the ASG will try each one in turn, use it to select the instance(s) to terminate, and if more than one instance matches the criteria, then use the next policy to try to break the tie. E.g., If you use ['OldestInstance', 'ClosestToNextInstanceHour'] and and there were two instances with exactly the same launch time, then the ASG would try the next policy, which is to terminate the one closest to the next instance hour in billing.
  # Type: list
  # termination_policies = ["OldestInstance"]

  # Description: Protect EC2 instances running ECS tasks from being terminated due to scale in (spot instances do not support lifecycle modifications)
  # Type: bool
  # autoscaling_termination_protection = false

  # Description: Enables or disables a graceful shutdown of instances without disturbing workloads.
  # Type: bool
  # autoscaling_managed_draining = true

  # Description: Enable a capacity provider to autoscale the EC2 ASG created for this ECS cluster
  # Type: bool
  capacity_provider_enabled = true

  # Description: Enable a multi-az capacity provider to autoscale the EC2 ASGs created for this ECS cluster, only if capacity_provider_enabled = true
  # Type: bool
  # multi_az_capacity_provider = false

  # Description: Target cluster utilization for the capacity provider; a number from 1 to 100.
  # Type: number
  # capacity_provider_target = 75

  # Description: Maximum step adjustment size to the ASG's desired instance count
  # Type: number
  # capacity_provider_max_scale_step = 10

  # Description: Minimum step adjustment size to the ASG's desired instance count
  # Type: number
  # capacity_provider_min_scale_step = 1

  # Description: A list of metrics to collect. The allowed values are GroupDesiredCapacity, GroupInServiceCapacity, GroupPendingCapacity, GroupMinSize, GroupMaxSize, GroupInServiceInstances, GroupPendingInstances, GroupStandbyInstances, GroupStandbyCapacity, GroupTerminatingCapacity, GroupTerminatingInstances, GroupTotalCapacity, GroupTotalInstances.
  # Type: list
  # cluster_asg_metrics_enabled = []

  # Description: Whether or not to enable Container Insights on the ECS cluster. Refer to https://docs.aws.amazon.com/AmazonECS/latest/developerguide/cloudwatch-container-insights.html for more information on ECS Container Insights.
  # Type: bool
  # enable_cluster_container_insights = false

  # Description: If you set this variable to false, this module will not create any resources. This is used as a workaround because Terraform does not allow you to use the 'count' parameter on modules. By using this parameter, you can optionally create or not create the resources within this module.
  # Type: bool
  # create_resources = true

  # Description: The ARN of the policy that is used to set the permissions boundary for the IAM role for the cluster instances.
  # Type: string
  # cluster_instance_role_permissions_boundary_arn = null

  # Description: The affinity setting for an instance on a Dedicated Host.
  # Type: string
  # cluster_instance_placement_affinity = null

  # Description: The name of the placement group for the instance.
  # Type: string
  # cluster_instance_placement_group_name = null

  # Description: The ID of the Dedicated Host for the instance.
  # Type: string
  # cluster_instance_placement_host_id = null

  # Description: The ARN of the Host Resource Group in which to launch instances.
  # Type: string
  # cluster_instance_placement_host_resource_group_arn = null

  # Description: The number of the partition the instance should launch in. Valid only if the placement group strategy is set to partition.
  # Type: number
  # cluster_instance_placement_partition_number = null

  # Description: Enables additional block device mapping. Change to false if you wish to disable additional EBS volume attachment to EC2 instances. Defaults to true.
  # Type: bool
  # enable_block_device_mappings = true

  # Description: The required duration in minutes. This value must be a multiple of 60.
  # Type: number
  # cluster_instance_market_block_duration_minutes = null

  # Description: The behavior when a Spot Instance is interrupted. Can be hibernate, stop, or terminate. (Default: terminate).
  # Type: string
  # cluster_instance_market_instance_interruption_behavior = "terminate"

  # Description: The Spot Instance request type. Can be one-time, or persistent.
  # Type: string
  # cluster_instance_market_spot_instance_type = null

  # Description: The end date of the request.
  # Type: string
  # cluster_instance_market_valid_until = null

  # Description: The name of the device to mount.
  # Type: string
  # cluster_instance_block_device_name = "/dev/xvdcz"

  # Description: Whether the volume should be destroyed on instance termination. Defaults to false
  # Type: bool
  # cluster_instance_ebs_delete_on_termination = false

  # Description: The amount of provisioned IOPS. This must be set with a volume_type of io1/io2.
  # Type: string
  # cluster_instance_ebs_iops = null

  # Description: The ARN of the AWS Key Management Service (AWS KMS) customer master key (CMK) to use when creating the encrypted volume. The variable cluster_instance_root_volume_encrypted must be set to true when this is set.
  # Type: string
  # cluster_instance_ebs_kms_key_id = null

  # Description: The Snapshot ID to mount.
  # Type: string
  # cluster_instance_ebs_snapshot_id = null

  # Description: The throughput to provision for a gp3 volume in MiB/s (specified as an integer, e.g., 500), with a maximum of 1,000 MiB/s.
  # Type: number
  # cluster_instance_ebs_throughput = null

  # Description: Maximum amount of time, in seconds, that an instance can be in service, values must be either equal to 0 or between 86400 and 31536000 seconds.
  # Type: number
  # max_instance_lifetime = null

  # Description: Strategy to use for instance refresh. If not specified then instance_refresh is disabled
  # Type: string
  # instance_refresh_strategy = null

  # Description: Override default parameters for Instance Refresh. See https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_group#preferences for available options
  # Type: map
  # instance_refresh_preferences = {}
}
